let n = 0, m = 100;
//let n = 2, m = 5;
//let n = 100, m = -5;
//let n = -3, m = -10;
let min = Math.min(n, m);
let max = Math.max(n, m);
let NumberInRange = Math.floor(Math.random() * ((max - 1) - min) + min);
let EvenRandom = NumberInRange - (NumberInRange % 2);
let OddRandom = Math.floor(EvenRandom + 1);
console.log(OddRandom);