let Name = 'грЖегоРЖ';
let Surname = 'БжеДЗИСТикевиЧ';
let NameFirstLetter = Name.substr(0, 1);
let NameRestWord = Name.substr(1);
let SurnameFirstLetter = Surname.substr(0, 1);
let SurnameRestWord = Surname.substr(1);
let CorrectName = NameFirstLetter.toUpperCase() + NameRestWord.toLowerCase();
let CorrectSurname = SurnameFirstLetter.toUpperCase() + SurnameRestWord.toLowerCase();
Name === CorrectName ? console.log('Имя осталось без изменений') : console.log('Имя было преобразовано');
Surname === CorrectSurname ? console.log('Фамилия осталась без изменений') : console.log('Фамилия была преобразована');
console.log(CorrectName + ' ' + CorrectSurname);
